---
functional:
- Пользователь должен иметь возможность искать товары по ключевому слову или категории
- Пользователь должен иметь возможность фильтровать товары
- Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
- sПользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
- Сайт должен иметь мобильную версию
- Важно, чтобы сайт мог обрабатывать большое количество трафика
- Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
- Сайт должен быть безопасным и защищать данные пользователя
- Сайт нужно протестировать на совместимость с последними версиями браузеров
- Важно, чтобы сайт мог обрабатывать большое количество трафика
- Сайт должен быть доступен на различных устройствах
implicit:
- В поля ввода цены нельзя вводить отрицательные значения
- Должна быть возможность сброса категории фильтров
- Должна быть возможность просмотра товара который скоро будет доступен в магазине
- Должна быть возможность вернуться на главную страницу магазина при нажатии на логотип сайта
- Нельзя добавлять в корзину товары неавторизованным пользователям
- Должна быть возможность сброса пароля
- Должно быть ограничение на количество товаров для заказа (если товар есть в наличии)
